<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(LibraryTargetFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>WLED</PackageId>
    <Title>WLED.NET</Title>
    <PackageTags>WLED</PackageTags>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Description>A .NET Wrapper around the WLED JSON API.</Description>
    <IsPackable>True</IsPackable>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../icon.png" Pack="true" Visible="false" PackagePath="" />
    <None Include="../../README.md" Pack="true" Visible="false" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Kevsoft.WLED.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="System.Net.Http.Json" Version="6.0.0" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>
  
</Project>
