<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(LibraryTargetFrameworks)</TargetFrameworks>
    <RootNamespace>Kevsoft.WLED</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>WLED.DependencyInjection</PackageId>
    <Title>WLED.NET Dependency Injection</Title>
    <PackageTags>WLED;DependencyInjection;IHttpClientFactory</PackageTags>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Description>Microsoft.Extensions.DependencyInjection integration for WLED.NET.</Description>
    <IsPackable>True</IsPackable>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../icon.png" Pack="true" Visible="false" PackagePath="" />
    <None Include="../../README.md" Pack="true" Visible="false" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Kevsoft.WLED/Kevsoft.WLED.csproj" />
  </ItemGroup>

</Project>
